name: Github Actions CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v1
    - name: Compile Resume
      uses: xu-cheng/latex-action@master
      with:
        root_file: main.tex
        working_directory: .
        args: "-xelatex -shell-escape -file-line-error -interaction=nonstopmode"
    - name: Check pdf files
      run: |
        file main.pdf | grep -q ' PDF '
    - name: Upload
      run: |
        # configure git
        git config --global user.name "Mukul Hase"
        git config --global user.email "mukulhase@gmail.com"

        # setup ssh
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        git config --global core.sshCommand "ssh -i ~/.ssh/id_ed25519 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

        git clone --depth=1 --branch gh-pages git@github.com:mukulhase/Mukul_Hase_Resume.git "$GITHUB_WORKSPACE/deploy"
        cp -f main.pdf "$GITHUB_WORKSPACE/deploy/main.pdf"
        cd "$GITHUB_WORKSPACE/deploy"
        git add main
        git commit -m "[github actions] deploy"
        git push
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
