name: Github Actions CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v1
    - name: Compile Resume
      uses: xu-cheng/latex-action@master
      with:
        root_file: main.tex
        working_directory: .
        args: "-xelatex -shell-escape -file-line-error -interaction=nonstopmode"
    - name: Check pdf files
      run: |
        file main.pdf | grep -q ' PDF '
        mkdir publish
        cp main.pdf publish/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish
